apiVersion: apps/v1
kind: Deployment
metadata:
  name: kol2022-g3-main-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kol2022-g3-main-app
  template:
    metadata:
      labels:
        app: kol2022-g3-main-app
    spec:
      containers:
        - name: kol2022-g3-main-app
          image: kol2022-g3-main-app:latests
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: h2-data
              mountPath: /data/h2
      volumes:
        - name: h2-data
