apiVersion: v1
kind: Service
metadata:
  name: kol2022-g3-main-service
spec:
  selector:
    app: kol2022-g3-main-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
